version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Sao_Paulo
    open-pull-requests-limit: 10
    labels:
      - dependencies
    commit-message:
      prefix: ':arrow_up: build'
      include: scope
    groups:
      django:
        patterns:
          - 'django*'
          - 'djangorestframework*'
          - 'drf-*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
