# Generated by Django 5.2.17 on 2026-10-02 19:36

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        UnaccentExtension(),
    ]
