# Generated by Django 5.2.17 on 2026-10-07 15:21

import apps.accounts.models.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unaccent_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storedfile',
            name='file',
            field=models.FileField(help_text='File to be stored', max_length=255, upload_to=apps.accounts.models.files.upload_to_storage_files, verbose_name='File'),
        ),
    ]
