# Generated by Django 5.2.18 on 2026-10-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Português (Brasil)')], default='en', help_text="Language used to render this user's emails.", max_length=8, verbose_name='Preferred Language'),
        ),
    ]
