# Generated by Django 5.2.15 on 2026-06-09 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Is this record active or not',
                        verbose_name='Is Active',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='When the record was initially created',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='When the record was last updated',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Name of the team',
                        max_length=100,
                        verbose_name='Name',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        help_text='Team slug', unique=True, verbose_name='Slug'
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True,
                        help_text='Description of the team',
                        null=True,
                        verbose_name='Description',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who created the record',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        help_text='Organization to which the team belongs',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teams',
                        to='accounts.organization',
                        verbose_name='Organization',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who last updated the record',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-id'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Is this record active or not',
                        verbose_name='Is Active',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='When the record was initially created',
                        verbose_name='Created At',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        help_text='When the record was last updated',
                        verbose_name='Updated At',
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('owner', 'Owner'),
                            ('admin', 'Admin'),
                            ('manager', 'Manager'),
                            ('member', 'Member'),
                        ],
                        default='member',
                        help_text='Role of the member in the team',
                        max_length=20,
                        verbose_name='Role',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who created the record',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Created By',
                    ),
                ),
                (
                    'member',
                    models.ForeignKey(
                        help_text='Member of the team',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='teams',
                        to='accounts.member',
                        verbose_name='Member',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        help_text='Team to which this member belongs',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='members',
                        to='teams.team',
                        verbose_name='Team',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        help_text='User who last updated the record',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Updated By',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['-id'],
                'unique_together': {('team', 'member')},
            },
        ),
    ]
