# Generated by Django 5.2.17 on 2026-09-28 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(help_text='Team slug', verbose_name='Slug'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('name', 'organization'), name='unique_name_org_when_active', violation_error_message='This team already exists.'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('slug', 'organization'), name='unique_slug_org_when_active', violation_error_message='This team already exists.'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('team', 'member'), name='unique_team_member_when_active', violation_error_message='This member is already part of the team.'),
        ),
    ]
